/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;

/**
 *
 * @author gustavomiara
 */
public class SelectedPlayers extends javax.swing.JFrame {

    /**
     * Creates new form SelectedPlayers
     */
    public SelectedPlayers() {

        initComponents();
        playerOneJpanel.setOpaque(true);
        playerTwoJpanel.setOpaque(true);
        playerOneJpanel.setBackground(new Color(0, 0, 0, 0));
        playerTwoJpanel.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playerOneJpanel = new javax.swing.JPanel();
        monsterButton = new javax.swing.JButton();
        heroeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        playerTwoJpanel = new javax.swing.JPanel();
        monsterButton1 = new javax.swing.JButton();
        heroeButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JavaRPG - Selected Players");
        setPreferredSize(new java.awt.Dimension(800, 710));
        setResizable(false);
        getContentPane().setLayout(null);

        playerOneJpanel.setBackground(new java.awt.Color(254, 254, 254));
        playerOneJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(251, 0, 0)), "PLAYER 1", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(254, 6, 6))); // NOI18N
        playerOneJpanel.setForeground(new java.awt.Color(254, 1, 1));
        playerOneJpanel.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        playerOneJpanel.setPreferredSize(new java.awt.Dimension(584, 335));

        monsterButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/darkglorysson.png"))); // NOI18N
        monsterButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monsterButton.setPreferredSize(new java.awt.Dimension(190, 299));
        monsterButton.setSelected(true);

        heroeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montaro.png"))); // NOI18N
        heroeButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        heroeButton.setPreferredSize(new java.awt.Dimension(190, 299));
        heroeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroeButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Heroes");

        jLabel2.setText("Monster");

        javax.swing.GroupLayout playerOneJpanelLayout = new javax.swing.GroupLayout(playerOneJpanel);
        playerOneJpanel.setLayout(playerOneJpanelLayout);
        playerOneJpanelLayout.setHorizontalGroup(
            playerOneJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerOneJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monsterButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(heroeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        playerOneJpanelLayout.setVerticalGroup(
            playerOneJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerOneJpanelLayout.createSequentialGroup()
                .addGroup(playerOneJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monsterButton, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(heroeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(playerOneJpanel);
        playerOneJpanel.setBounds(12, 0, 584, 335);

        playerTwoJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 0, 0)), "PLAYER 2", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(246, 1, 4))); // NOI18N
        playerTwoJpanel.setForeground(new java.awt.Color(255, 0, 0));
        playerTwoJpanel.setPreferredSize(new java.awt.Dimension(576, 300));

        monsterButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/darkglorysson.png"))); // NOI18N
        monsterButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monsterButton1.setPreferredSize(new java.awt.Dimension(190, 299));
        monsterButton1.setSelected(true);

        heroeButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/montaro.png"))); // NOI18N
        heroeButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        heroeButton1.setPreferredSize(new java.awt.Dimension(190, 299));
        heroeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heroeButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout playerTwoJpanelLayout = new javax.swing.GroupLayout(playerTwoJpanel);
        playerTwoJpanel.setLayout(playerTwoJpanelLayout);
        playerTwoJpanelLayout.setHorizontalGroup(
            playerTwoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerTwoJpanelLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(monsterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(heroeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        playerTwoJpanelLayout.setVerticalGroup(
            playerTwoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerTwoJpanelLayout.createSequentialGroup()
                .addGroup(playerTwoJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monsterButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(heroeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(playerTwoJpanel);
        playerTwoJpanel.setBounds(12, 341, 584, 335);

        jButton1.setText("Arena");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(600, 30, 186, 29);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgSelectedPLayers.jpeg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-3, 0, 800, 710);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void heroeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heroeButtonActionPerformed

    private void heroeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heroeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heroeButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Arena arena = new Arena();
        arena.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectedPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectedPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectedPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectedPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectedPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton heroeButton;
    private javax.swing.JButton heroeButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton monsterButton;
    private javax.swing.JButton monsterButton1;
    private javax.swing.JPanel playerOneJpanel;
    private javax.swing.JPanel playerTwoJpanel;
    // End of variables declaration//GEN-END:variables
}
